### ISSUE TITLE
 java.io.IOException: No such file or directory in H3Core.newInstance()

### ISSUE THREAD

**Issue by plluo** [uber/h3-java#101]
Hi team, I am using H3.3.6.3 in a Buildkite job. The job will run Java Jar dozens of times to process different files. Each time, it initializes an H3 instance. It works fine at first. And It throws an exception near the end. The Buildkite image is based on Debian buster which has Glibc version 2.23. 

`

Exception in thread "main" java.lang.ExceptionInInitializerError
--
  | Caused by: java.lang.RuntimeException: java.io.IOException: No such file or directory
  | ... 3 more
  | Caused by: java.io.IOException: No such file or directory
  | at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
  | at java.base/java.io.File.createTempFile(File.java:2129)
  | at java.base/java.io.File.createTempFile(File.java:2175)
  | at com.uber.h3core.H3CoreLoader.loadNatives(H3CoreLoader.java:112)
  | at com.uber.h3core.H3CoreLoader.loadNatives(H3CoreLoader.java:87)
  | at com.uber.h3core.H3Core.newInstance(H3Core.java:79)
  | ... 3 more

`

**Comment by isaacbrodsky** [comment]
This seems to be a failure to extract the native library part of the JAR to the file system. Is it possible the temporary directory is being cleaned up from the job before it has actually completed? Can you try placing the temporary file elsewhere (following the instructions here: https://stackoverflow.com/questions/1924136/environment-variable-to-control-java-io-tmpdir) and see if the issue persists?

**Comment by plluo** [comment]
Thank you @isaacbrodsky. It worked.
