### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by isaacbrodsky** [uber/h3-java#4]
The built artifact should get published to Maven Central so it can be easily used.

**Comment by kindjacket** [comment]
@isaacbrodsky I see the PR has been merged. Any idea when it will be published to Maven central? Currently I can't see it there.

**Comment by isaacbrodsky** [comment]
Hi @kindjacket, I'll perform the release once #12 is merged. That should get done later today or tomorrow.

**Comment by kindjacket** [comment]
awesome! thanks @isaacbrodsky!
