### ISSUE TITLE
RuntimePermission error when trying to load the H3 Java library

### ISSUE THREAD

**Issue by consulthys** [uber/h3-java#51]
Hi guys,

As I read on the general [H3 roadmap](https://github.com/uber/h3/wiki/Roadmap) that some help was welcome to integrate H3 with Elasticsearch, I decided to create an Elasticsearch [ingest processor](https://www.elastic.co/guide/en/elasticsearch/reference/current/ingest-processors.html) that provides support for creating H3 indexes on the fly given a geo location point. 

The new processor is packaged as an Elasticsearch plugin and deployed on Elastic Cloud. The plugin instantiates the library using:

        H3Core h3 = H3Core.newInstance();

However, when I make use of the `ingest-h3` processor, I'm getting the following error:

          "error" : {
            "root_cause" : [
              {
                "type" : "access_control_exception",
                "reason" : """access denied ("java.lang.RuntimePermission" "loadLibrary./tmp/elasticsearch-4590080898583617881/libh3-java12293578950618569557.so")"""
              }
            ],
            "type" : "access_control_exception",
            "reason" : """access denied ("java.lang.RuntimePermission" "loadLibrary./tmp/elasticsearch-4590080898583617881/libh3-java12293578950618569557.so")"""
          }

Trying to use `H3Core.newSystemInstance()` yields a similar error, which makes more sense since the `h3-java` native library is not installed system-wide:

          "error" : {
            "root_cause" : [
              {
                "type" : "access_control_exception",
                "reason" : """access denied ("java.lang.RuntimePermission" "loadLibrary.h3-java")"""
              }
            ],
            "type" : "access_control_exception",
            "reason" : """access denied ("java.lang.RuntimePermission" "loadLibrary.h3-java")"""
          }

It's also worth noting that in the [`plugin-security.policy` file](https://www.elastic.co/guide/en/elasticsearch/plugins/7.4/plugin-authors.html#plugin-authors-jsm) I have added the following permission:

     permission java.lang.RuntimePermission "loadLibrary.*";

I'm a bit out of solutions and not sure how I can have the H3 native library loaded. If anyone can help shed some light on this, it'd be much appreciated. Thanks!

**Comment by isaacbrodsky** [comment]
Great to hear you're interested in that!

I'm unsure about Elastic Cloud itself, but when installing locally you should see a security warning message like the following. Are you getting this warning, does it have the `loadLibrary` permission, and does the plugin work on a local Elasticsearch instance?

```
$ ./bin/elasticsearch-plugin install file:///....zip
-> Downloading file:///....zip
[=================================================] 100%
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission accessDeclaredMembers
<other lines elided>
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.

Continue with installation? [y/N]
```

**Comment by consulthys** [comment]
Thanks for your feedback @isaacbrodsky !

I've also tried locally of course and it yields pretty much the same error (except that I'm on a Mac)

The installation procedure locally looks like this:

```
iMac:elasticsearch-7.4.0 val$ bin/elasticsearch-plugin install file:///Users/val/workspaces/elasticsearch-ingest-h3/build/distributions/ingest-h3-1.0.0-SNAPSHOT.zip
-> Downloading file:///Users/val/workspaces/elasticsearch-ingest-h3/build/distributions/ingest-h3-1.0.0-SNAPSHOT.zip
[=================================================] 100%   
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission loadLibrary.*
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.

Continue with installation? [y/N]y
-> Installed ingest-h3
iMac:elasticsearch-7.4.0 val$ bin/elasticsearch
```

But then when using the processor, I get a similar error

              access denied ("java.lang.RuntimePermission" "loadLibrary./private/var/folders/cm/1qlt35594tqcbc16d__qndw40000gs/T/elasticsearch-13266134356621733061/libh3-java17825198635206763514.dylib")

**Comment by isaacbrodsky** [comment]
I think this has to do with how the Java security manager treats the additional permissions for the plugins. I was able to reproduce the issue, and then get a plugin to load H3 by wrapping the initialization code like so:

```
      final H3Core h3 =
          AccessController.doPrivileged(
              (PrivilegedExceptionAction<H3Core>)
                  (() -> {
                    return H3Core.newInstance();
                  }));
```

**Comment by consulthys** [comment]
Indeed I tried the same thing and it worked out. Thanks for your help, much appreciated!

**Comment by consulthys** [comment]
For those who're interested the H3 ingest processor repo is here: https://github.com/consulthys/elasticsearch-ingest-h3

Still a lot of work to do, but the building blocks are there!
