### ISSUE TITLE
H3-java newInstance() couldn't recover when the temporary dynamic library file is deleted

### ISSUE THREAD

**Issue by boyxgc** [uber/h3-java#58]
When newing an H3Core instance, the function copies the dynamic library from resources to a temporary file in order to load the libraries and reuses the original temporary file for newing instances later. 

In the event that the temporary file is deleted, creating new instances always crashes with no way to recover. 

I suggest we add a file existence check to the existing file path and recreate if needed.

**Comment by isaacbrodsky** [comment]
I think adding a file existence check makes sense. There will still be a race condition where the file is determined to exist and then is deleted (unless catching the file not found exception)

**Comment by boyxgc** [comment]
This is fixed in the v3.6.3 release.
