### ISSUE TITLE
Run H3-java on CentOS 6.6 Spark Cluster

### ISSUE THREAD

**Issue by ce39906** [uber/h3-java#62]
@isaacbrodsky @dfellis 
I'm using H3-java on CentOS 6.6 spark cluster of my company, when I new H3Core instance,  the error log shows that Glibc2.14 was not found.
Could you compile a "libh3-java.so" on CentOS 6.6 for me？ That would be very grateful！

**Comment by isaacbrodsky** [comment]
Hi, are you or the cluster’s operator able to run “mvn package” on this repo? This would be the most likely to work as building in your environment would use the specific libc version needed.

**Comment by ce39906** [comment]
Hi, @isaacbrodsky ，i downloaded the latest code and compile them on my CentOS 6.6 server. My GCC version is 5.3.1. I change the CMakeLists.txt as follows.
[CMakeLists.txt](https://github.com/uber/h3-java/files/4768426/CMakeLists.txt)

After `cmake3 . && make`
there is h3's dynamic library as bellow
![image](https://user-images.githubusercontent.com/10767336/84458681-2b51a980-ac98-11ea-88cf-909af84b600b.png)
When I do `sudo make install`, there is an error as bellow
![image](https://user-images.githubusercontent.com/10767336/84459023-fdb93000-ac98-11ea-83e3-71bedb7beb79.png)

I rename libh3.so.1 to libh3-java.so and package it to my jar.
when I run my spark job. it still shows UnsatisfiedLinkError as bellow
`java.lang.UnsatisfiedLinkError: com.uber.h3core.NativeMethods.geoToH3(DDI)J
	at com.uber.h3core.NativeMethods.geoToH3(Native Method)
	at com.uber.h3core.H3Core.geoToH3(H3Core.java:169)
	at com.uber.h3core.H3Core.geoToH3Address(H3Core.java:188)
	at com.sankuai.map.routing.spark.lambdafeature.util.PolyLineUtils$1.apply(PolyLineUtils.java:63)`

**Comment by dfellis** [comment]
So for some reason the version numbers aren't being replaced correctly in the C source code.

Can you paste the result of `cmake --version` as well as the *entirety* of the logs from `cmake3 . && make`? I suspect some tool is missing that isn't properly stopping the `make` command with an error.

**Comment by isaacbrodsky** [comment]
Also, I don’t believe the Java bindings will work with a renamed libh3. As the error message indicates Java needs some additional functions not present in the libh3. These functions are compiled in when you build H3-Java itself (it compiles it’s own copy of the library with an additional file, or you could build the library from that repos build script)

**Comment by ce39906** [comment]
> So for some reason the version numbers aren't being replaced correctly in the C source code.
> 
> Can you paste the result of `cmake --version` as well as the _entirety_ of the logs from `cmake3 . && make`? I suspect some tool is missing that isn't properly stopping the `make` command with an error.

![image](https://user-images.githubusercontent.com/10767336/84470186-55659480-acb5-11ea-9fde-707e4a254f89.png)
![image](https://user-images.githubusercontent.com/10767336/84470238-79c17100-acb5-11ea-99b0-e61cbbb60f74.png)
![image](https://user-images.githubusercontent.com/10767336/84470250-81811580-acb5-11ea-91dd-cc49a6b5acc6.png)
In CMakeLists.txt, I turned off these four options.
![image](https://user-images.githubusercontent.com/10767336/84470277-9493e580-acb5-11ea-955e-deb251e04793.png)

**Comment by ce39906** [comment]
> ou could build the library from that repos build scri



> Also, I don’t believe the Java bindings will work with a renamed libh3. As the error message indicates Java needs some additional functions not present in the libh3. These functions are compiled in when you build H3-Java itself (it compiles it’s own copy of the library with an additional file, or you could build the library from that repos build script)

Thanks, where can I find the repositories for building libh3-java.so?

**Comment by isaacbrodsky** [comment]
That’s the repo this issue is on, uber/h3-java

**Comment by ce39906** [comment]
> libh3-java is built as part of the repo this issue is on, uber/h3-java.

@isaacbrodsky 
I cloned the repo and cp build-h3.sh to repo root dir.
Then I compile like this
`
sudo ./build-h3.sh https://github.com/uber/h3.git v3.6.2
`
The error log is below.

![image](https://user-images.githubusercontent.com/10767336/84481756-20633d00-acc9-11ea-88f3-0aed2f55b07e.png)
![image](https://user-images.githubusercontent.com/10767336/84481821-4688dd00-acc9-11ea-8e13-f08db22d94a9.png)

**Comment by ce39906** [comment]
> libh3-java is built as part of the repo this issue is on, uber/h3-java.

I config maven on my CentOS 6.6 server and run 
`sudo mvn package`
After the package, the libh3-java.so is available. Thank you again @isaacbrodsky @dfellis
