### ISSUE TITLE
Update H3 Docs to allow usage example language toggle

### ISSUE THREAD

**Issue by dfellis** [uber/h3-java#7]
The README tells the users of h3-java to refer to the H3 docs, but all of the examples there are in C.

We should add examples in Java, now, and allow the reader to toggle between languages.

I'm willing to work on this, myself, but I figured there should be a discussion because:

1. The documentation will need to link to the h3-java project, as well.
2. Should the documentation only include examples in languages officially supported by Uber?
3. If not, what is the threshold for being considered for inclusion? 100% coverage of the API?

**Comment by isaacbrodsky** [comment]
100% coverage of the API and binding to a fairly up to date version of the core library seems reasonable as an inclusion guideline.

@nrabinowitz @joegilley What do you think?

**Comment by dfellis** [comment]
Update on the doc work part of this: The H3 docs depend on a package called [ocular](https://www.npmjs.com/package/ocular) which is published on NPM but doesn't have the source code on github/bitbucket/anywhere that I can find.

There are some issues with it to allow toggling between language examples in the same page when the pages are defined with Markdown (it's not flexible enough, basically). I would need to make changes to it to support that, first, but since it's not actually publicly-maintained code, I can't. :(

(Also, the syntax highlighting is broken because of the packages it depends on, so I can't tell it that the code is C or Java or etc, it's just guessing or not highlighting at all. I also can't fix that.)

So, should I rework the H3 docs significantly to not use Ocular anymore, inline the Ocular code and fork it, or can we track down the person who made Ocular and get him to make it open so we can fix it upstream?

**Comment by nrabinowitz** [comment]
I believe the Ocular maintainer is @apercu. I'm not sure why they haven't open-sourced it or put it on GH. I'll reach out. I'd rather keep the docs on Ocular for the moment, for consistency with other doc sites (e.g. deck.gl)

**Comment by balthazar** [comment]
The [repo](http://github.com/uber-web/ocular) is still private under the uber-web org, not sure if there is plans to open-source it for now @ibgreen?

**Comment by ibgreen** [comment]
I just filed the open source application for ocular (it looks like we never got around to it).

As soon as we have approval, I will flip the public switch. In the mean time I can give access to the repo, but only to internal folks.

**Comment by dfellis** [comment]
Well, the code is already open source on the npm registry. Do you want to take it down from there for now?

**Comment by ibgreen** [comment]
Yes, that is true, at least the transpiled code would be there.

But not sure how easy removing it would be. I am under the impression that npm disabled unpublishing of packages after the leftPad debacle.

Also removing it now would cause work for all projects that are importing it from npm (quite a few internally).

Given that this is a simple document generator module, let's keep as is for now, and we'll make sure to avoid this situation going forward.
