### ISSUE TITLE
OperatingSystem Enum , getDirName toLowerCase() causes UnsatisfiedLinkError for Turkish Local

### ISSUE THREAD

**Issue by brkyc3** [uber/h3-java#79]
Hi,

I have a problem, when i try to H3Core.newInstance(), it throws an exception like this 

"No native resource found at /darwın-x64/libh3-java.dylib ...." Not darwin but darwın.

under OperatingSystem Enum getDirName , i saw toLowerCase used with default local, it causes problem on Turkish  lang (may be some other languages have this problem too) , can u change it like, 

`toLowerCase()`
-->
`toLowerCase(Locale.ENGLISH)`

Or do you have any suggestion for bypassing this without completely changing system locale to English ?

**Comment by isaacbrodsky** [comment]
Thanks for reporting this - it definitely looks like the locale issue you mentioned. I'll submit a pull request to try to address this.

Unfortunately I do not think there is a way to work around this without patching the library, or compiling h3-java's native library component yourself.
